### ISSUE TITLE
Toolbar Not Available on Content Block Creation

### ISSUE THREAD

**Issue by yee-luna-c** [alexanderlewis99/TinyMCEMod#2]
When initially creating a content block (with a text element) on a page, the TinyMCEMod toolbar is not accessible; instead, the default toolbar appears.

![image](https://user-images.githubusercontent.com/43069771/56163570-417cb080-5f94-11e9-827f-ac7851007b29.png)
*Above: a newly-created text block. Below: the same text block after saving the page and refreshing.*
![image](https://user-images.githubusercontent.com/43069771/56163765-c5369d00-5f94-11e9-94a7-f4bd50e99e31.png)

This seems to be due to the fact that the WYSIWIG interface is loaded dynamically when a new text block is introduced&mdash;after the page has been loaded.

**Comment by alexanderlewis99** [comment]
Thanks for bringing this up. I had code that resolved this, but I must have accidentally deleted it in a previous commit. I reinserted that code and now new blocks have the modded toolbar without refreshing.

**Comment by apjmason** [comment]
Fixed in b94acea5bfb002592a9b851fb5b2ecf327450a82
